apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubevpn
spec:
  version: {{ .TagName }}
  homepage: https://github.com/kubenetworks/kubevpn
  shortDescription: "KubeVPN offers a Cloud Native Dev Environment that connects to kubernetes cluster network"
  description: |
    KubeVPN offers a Cloud-Native Dev Environment that seamlessly connects to your Kubernetes cluster network.
    Gain access to the Kubernetes cluster network effortlessly using service names or Pod IP/Service IP. Facilitate the interception of inbound traffic from remote Kubernetes cluster services to your local PC through a service mesh and more.
    For instance, you have the flexibility to run your Kubernetes pod within a local Docker container, ensuring an identical environment, volume, and network setup. With KubeVPN, empower yourself to develop applications entirely on your local PC!

  platforms:
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_windows_amd64.zip" .TagName }}
    files:
      - from: ./bin/kubevpn.exe
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_windows_arm64.zip" .TagName }}
    files:
      - from: ./bin/kubevpn.exe
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn.exe
  - selector:
      matchLabels:
        os: windows
        arch: 386
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_windows_386.zip" .TagName }}
    files:
      - from: ./bin/kubevpn.exe
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn.exe
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_linux_amd64.zip" .TagName }}
    files:
      - from: ./bin/kubevpn
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_linux_arm64.zip" .TagName }}
    files:
      - from: ./bin/kubevpn
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn
  - selector:
      matchLabels:
        os: linux
        arch: 386
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_linux_386.zip" .TagName }}
    files:
      - from: ./bin/kubevpn
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_darwin_amd64.zip" .TagName }}
    files:
      - from: ./bin/kubevpn
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/kubenetworks/kubevpn/releases/download/{{ .TagName }}/kubevpn_{{ .TagName }}_darwin_arm64.zip" .TagName }}
    files:
      - from: ./bin/kubevpn
        to: .
      - from: LICENSE
        to: .
    bin: kubevpn