# Here is an example config kubevpn config file, please change it into your custom config.
# Support three filed: Name,Needs,Flags
# Exec command: kubevpn alias qa <===> kubevpn connect --kubeconfig=~/.kube/jumper_config --namespace=default
# Just keep simple

Name: dev
Description: This is dev k8s environment, needs jump by qa env
Needs: qa
Flags:
  - connect
  - --kubeconfig=~/.kube/config
  - --namespace=default

---

Name: qa
Description: This is QA k8s environment
Flags:
  - connect
  - --kubeconfig=~/.kube/jumper_config
  - --namespace=default