# Here is an example config kubevpn config file, please change it into your custom config.
# Support three filed: Name,Needs,Flags
# Exec command: kubevpn alias qa === kubevpn connect --kubeconfig /Users/naison/.kube/jumper_config --namespace default
# Simple is Good ~

Name: dev
Needs: qa
Flags:
  - connect
  - --kubeconfig /Users/naison/.kube/config
  - --namespace default
  - --lite

---

Name: qa
Flags:
  - connect
  - --kubeconfig /Users/naison/.kube/jumper_config
  - --namespace default