apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubevpn.fullname" . }}
data:
  DHCP: ""
  DHCP6: ""
  ENVOY_CONFIG: ""
  IPv4_POOLS: "{{ .Values.cidr.pod }} {{ .Values.cidr.service }}"
  REF_COUNT: "0"
