apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevpn.fullname" . }}
  namespace: {{ include "kubevpn.namespace" . }}
  labels:
    {{- include "kubevpn.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubevpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kubevpn.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubevpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: vpn
          command:
            - kubevpn
          args:
            - server
            - -l gtcp://:10801
            - -l gudp://:10802
          envFrom:
            - secretRef:
                name: {{ include "kubevpn.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 10801
              name: 10801-for-tcp
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 10801
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 10801
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 10801
            initialDelaySeconds: 1
            periodSeconds: 2
            failureThreshold: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: false
        - name: control-plane
          command:
            - kubevpn
          args:
            - control-plane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9002
              name: 9002-for-envoy
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 1
            periodSeconds: 2
            failureThreshold: 15
          resources:
            {{- toYaml .Values.resourcesSmall | nindent 12 }}
        - name: dns
          command:
            - kubevpn
          args:
            - dns
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 53
              name: 53-for-dns
              protocol: UDP
          resources:
            {{- toYaml .Values.resourcesSmall | nindent 12 }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
