apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubevpn.fullname" . }}.{{ include "kubevpn.namespace" . }}
  namespace: {{ include "kubevpn.namespace" . }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      {{- $secret := (lookup "v1" "Secret" (include "kubevpn.namespace" .) (include "kubevpn.fullname" .)) }}
      {{- if $secret }}
      caBundle: {{ index $secret.data "tls_crt"  }}
      {{- else }}
      caBundle: {{ .Values.tls.crt }}
      {{- end }}
      service:
        name: {{ include "kubevpn.fullname" . }}
        namespace: {{ include "kubevpn.namespace" . }}
        path: /pods
        port: 80
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "kubevpn.fullname" . }}.naison.io
    namespaceSelector: { }
    objectSelector: { }
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - DELETE
        resources:
          - pods
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 15