apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubevpn.fullname" . }}
  namespace: {{ include "kubevpn.namespace" . }}
rules:
  - apiGroups:
      - ""
    resourceNames:
      - {{ include "kubevpn.fullname" . }}
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    resourceNames: ["{{ include "kubevpn.namespace" . }}"]
    verbs:
      - get
      - patch
  - apiGroups: [ "apps" ]
    resources: [ "deployments/scale", "deployments" ]
    resourceNames:
      - {{ include "kubevpn.fullname" . }}
    verbs:
      - get
      - update
      - patch
      - list
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubevpn.fullname" . }}.{{ include "kubevpn.namespace" . }}
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    resourceNames:
      - {{ include "kubevpn.fullname" . }}.{{ include "kubevpn.namespace" . }}
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch