apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubevpn.fullname" . }}
  namespace: {{ include "kubevpn.namespace" . }}
rules:
  - apiGroups:
      - ""
    resourceNames:
      - {{ include "kubevpn.fullname" . }}
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete