apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevpn.fullname" . }}
  namespace: {{ include "kubevpn.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevpn.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevpn.fullname" . }}
    namespace: {{ include "kubevpn.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubevpn.fullname" . }}.{{ include "kubevpn.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevpn.fullname" . }}
    namespace: {{ include "kubevpn.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubevpn.fullname" . }}.{{ include "kubevpn.namespace" . }}
  apiGroup: rbac.authorization.k8s.io
