apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevpn.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevpn.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevpn.fullname" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubevpn.fullname" . }}.{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevpn.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubevpn.fullname" . }}.{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
