apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevpn.fullname" . }}
  namespace: {{ include "kubevpn.namespace" . }}
type: Opaque
stringData:
  tls_crt: {{ .Values.tls.crt }}
  tls_key: {{ .Values.tls.key }}
  tls_server_name: {{ include "kubevpn.fullname" . }}.{{ include "kubevpn.namespace" . }}
