name: BuildTest

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-test:
    name: Build test
    strategy:
      fail-fast: false
      matrix:
        # ref https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        runner: ["ubuntu-24.04", "ubuntu-22.04", "macos-15-large", "macos-15-xlarge", "macos-14-large", "macos-14-xlarge", "macos-13-large", "macos-13-xlarge", "windows-2025", "windows-2022"]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build kubevpn
        run: |
          make kubevpn