name: Upload release

on:
  repository_dispatch:
    types: [ release-event ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ darwin, windows, linux ]
        arch: [ amd64, arm64, 386 ]
        exclude:
          - os: darwin
            arch: 386
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build kubevpn
        run: |
          TAG=`echo ${{ github.event.client_payload.tag }} | sed 's/refs\/tags\///' | sed 's/\(.*\)-.*/\1/' | sed 's/-[0-9]*$//' || true`
          git tag ${TAG} || true
          export GitHubOAuthToken=${{ secrets.KUBEVPN_UPGRADE_OAUTH }}
          make kubevpn-${{ matrix.os }}-${{ matrix.arch }}
          SUFFIX=""
          if [${{ matrix.os }} == "windows"]; then
            SUFFIX=".exe"
          fi
          
          shasum -a 256 ./bin/kubevpn-${{ matrix.os }}-${{ matrix.arch }}${SUFFIX} | awk '{print $1}' > checksums.txt
          zip -r kubevpn_${TAG}_${{ matrix.os }}_${{ matrix.arch }}.zip ./bin/kubevpn-${{ matrix.os }}-${{ matrix.arch }}${SUFFIX} LICENSE README.md README_ZH.md checksums.txt

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.client_payload.url }}
          asset_path: ./kubevpn_`echo ${{ github.event.client_payload.tag }} | sed 's/refs\/tags\///' | sed 's/\(.*\)-.*/\1/' | sed 's/-[0-9]*$//' || true`_${{ matrix.os }}_${{ matrix.arch }}.zip
          asset_name: kubevpn_`echo ${{ github.event.client_payload.tag }} | sed 's/refs\/tags\///' | sed 's/\(.*\)-.*/\1/' | sed 's/-[0-9]*$//' || true`_${{ matrix.os }}_${{ matrix.arch }}.zip
          asset_content_type: application/zip
  wait:
    needs: build
    name: Update brew
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.43
        with:
          krew_template_file: .github/krew.yaml

